version: "4"
services:
  backend_api:
    container_name: backend_api_container
    image: backend_api_img
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
  frontend_api:
    container_name: frontend_api_container
    image: frontend_api_img
    build:
      context: ./rontend/
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
  ml_api:
    container_name: ml_api_container
    image: ml_api_img
    build:
      context: ./ml/
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    environment:
      - LOG_LEVEL=INFO
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
